spring.datasource.url=jdbc:postgresql://localhost:5433/ecommerce
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
app.jwt.secret=483c256739eefd53b6b2c2ff549cec1ffad50e0365bf08ec8836d9dc8a9ee291
app.jwt.expiration=86400000